version: "3"

services:
  training: 
    image: alec892/orbis-training-docker:1.0.0
    build: .
    container_name: 'orbis-training-docker_training'
    ports: 
      - '1042:1042'
      - '35729:35729'
    volumes:
      - ./:/app