version: "3"

services:

  training: 
    image: alec892/orbis-training-docker:1.0.0
    build: .
    container_name: 'orbis-training-docker_training'
    ports: 
      - '1042:1042'
      - '35729:35729'
    volumes:
      - ./:/app
  
  test: 
    image: node:10.10.0-slim
    container_name: 'node_test'
    depends_on:
      - training
    #entrypoint: curl http://orbis-training-docker_training:1042
    command: curl http://orbis-training-docker_training:1042